name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    name: Build thesis PDFs
    runs-on: ubuntu-latest
    container: { image: 'aergus/latex' }

    steps:
      - uses: actions/checkout@v5
      - name: Build the thesis
        run: latexmk thesis && latexmk abstract-cz && latexmk abstract-en
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Thesis
          path: |
            *.pdf

  verify:
    name: Verify PDF/A
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Get PDFs
        uses: actions/download-artifact@v5
      - name: Run VeraPDF in Docker
        run: |
          docker run --rm -v $PWD/Thesis:/pdfs ghcr.io/mff-cuni-cz/cuni-thesis-validator verify /pdfs/*.pdf | tee /dev/stderr | grep -qE 'nonCompliant="0" failedJobs="0"'
